services:
  web:
    build: .
    container_name: lignes-de-cretes-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - ./data:/app/data
    # depends_on:
    #   - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  # db:
  #   image: postgis/postgis:15-3.3
  #   container_name: lignes-de-cretes-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  static_volume:
  # db_data:
